# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FIT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   
  pod 'Alamofire', '~> 3.0'
  # Pods for FIT


  target 'FITTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FITUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

